vich_uploader:
    db_driver: orm

    mappings:
        heros:
            uri_prefix: /images/heros
            upload_destination: '%kernel.project_dir%/public/images/heros'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true